### ISSUE TITLE
[error]Error: C:\hostedtoolcache\windows\cosmosdt\1.7.0\x64\dt.exe failed with return code: 4294967295

### ISSUE THREAD

**Issue by roniadmon** [Winvision/vsts-tasks#15]
I'm using the Data Migration Tool task to export data from a cosmos Db to another and get this error.
Have you seen or heard of this? What should I do?

**Comment by PrakashRajanSakthivel** [comment]
Hi, I am also getting this error while doing data migration. I am taking a json file and updating the collection. Is there anything needs to be done from the pipeline?

I am using mongo API in cosmos. when I further check the logs in the pipeline, It says "Critical error: Error reading JObject from JsonReader. Path '', line 0, position 0.". here is my json file content

```
{
    "_id": "5fc73ab61914354e80945495",
    "clientId": "12",
    "clientName": "ClientName",
    "projectName": "string",
    "createdBy": "",
    "createdDate": "2020-12-02T06:56:54.498Z",
    "lastUpdatedBy": "",
    "lastUpdatedDate": "2020-12-02T06:56:54.498Z"
  }
```
