### ISSUE TITLE
File not found: '..\1.0.19\index.js' when executing  Cosmos DB Data Migration Tool task

### ISSUE THREAD

**Issue by istarion111** [Winvision/vsts-tasks#39]
**Describe the bug**
Versions 1.0.18 and 1.0.19 cannot be executed in azure pipelines (the pipeline was successfully executed on version 1.0.13).
The displayed error is:
##[error]File not found: 'C:\agent\_work\_tasks\DataMigrationTool_bcb9bcd6-0dcc-4c3a-8e13-c900df4dd6d9\1.0.19\index.js'
Current agent version is '3.220.0'
The index.js is indeed missing in the _tasks folder. index.ts is present in the folder.

**To Reproduce**
1. Create a pipeline with Cosmos DB Data Migration Tool
2. Run the pipeline

**Comment by Nimtz89** [comment]
@istarion111 Update in issue #37

**Comment by istarion111** [comment]
I confirm the issue with missing index.js is resolved.
