### ISSUE TITLE
Add possibility to 'Create or Update' collection.

### ISSUE THREAD

**Issue by StefanPuntNL** [Winvision/vsts-tasks#4]
It would be great to have an option that creates the collection when it doesn't exist yet, but updates it when it does.

**Comment by mlankamp** [comment]
Hi Stefan, this task container a bulk load tool and collection management. Using collection management you can create, delete and update collections.

In our own release, we create the collection (with high RU), do a bulk upload and then update the collection to a lower RU and set an new indexing policy.

If you need help, just let me know!

**Comment by StefanPuntNL** [comment]
Hi Michiel, I was hoping to use this task to provision my Cosmos DB collections which are part of a bigger solution. However, if I would use the "Create" collection task in a task group that is also used for update deployments of our solution, then this specific task fails during succeeding deployments. So an option to do a "Create or update" would be very welcome in my scenario. An alternative could be an option on the "Create" option like "Set task result to 'succeeded' even when database already exists".

**Comment by mlankamp** [comment]
Let me check, but I think the update task creates the collection if doesn't exist.

**Comment by mlankamp** [comment]
No it doesn't, I will add an option to the update task "Create collection if it doesn't exist".

**Comment by StefanPuntNL** [comment]
Awesome!

**Comment by ppluijten** [comment]
@StefanPuntNL, if I read your comment correctly you are using the **Create** collection action but it fails if the database/collection already exists?

> Hi Michiel, I was hoping to use this task to provision my Cosmos DB collections which are part of a bigger solution. However, if I would use the "Create" collection task in a task group that is also used for update deployments of our solution, then this specific task fails during succeeding deployments. So an option to do a "Create or update" would be very welcome in my scenario. An alternative could be an option on the "Create" option like "Set task result to 'succeeded' even when database already exists".

The **Create** action should create a _database_ if it does not already exist, but continue without changes to the database if it does. The same goes for the _collection_.

The **Update** action fails if the _database_ or _collection_ do not not exist however, so the "Create _database_ if it does not exist" and "Create _collection_ if it does not exist" options are valid future features.

**Comment by mlankamp** [comment]
Problem fixed in version 1.0.16
