### ISSUE TITLE
How to Create the DB prior to Collections

### ISSUE THREAD

**Issue by KZeronimo** [Winvision/vsts-tasks#6]
What is the recommendation for creating the Cosmos DB that is required prior to creating / updating collections

**Comment by KZeronimo** [comment]
I see - we add the Database=Foo to the connection string - I think I have the same fundamental problem as issue #4 - closing this issue

**Comment by ppluijten** [comment]
For future reference, the **Create** collection action creates a database if it does not exist, using the `Database=[databasename]` part of the connection string; the **Update** collection action does not (yet).
