### ISSUE TITLE
Syntax error in the "Enter Query" text box

### ISSUE THREAD

**Issue by ghost** [Winvision/vsts-tasks#9]
I am trying to migrate data from cosmos db collection to a json file in blob. I want to query the data  as simple as "select * from c". 

This works as expected when i run it from the copy migration tool locally (dev machine)

But when I add a VSTS task to do the same, I get the below mentioned error:

Command which is executing:
[command]C:\Damco1\_work\_tool\cosmosdt\1.7.0\x64\dt.exe /s:DocumentDB /s.ConnectionString:*** /s.Collection:RejectedBookingList "/s.Query:\"SELECT RejectedBookingList.BookingNumber from RejectedBookingList\"" /t:JsonFile /t.File:C:\Damco1\_work\25\a\Order\rejectedbookinglist.json

ERROR Message:

Critical error: {"errors":[{"severity":"Error","location":{"start":0,"end":67},"code":"SC1001","message":"Syntax error, incorrect syntax near '\"SELECT RejectedBookingList.BookingNumber from RejectedBookingList\"'."}]}

**Comment by ghost** [comment]
I have tried with multiple permutations in the query box

for ex: select c.BookingNumber from c

**Comment by mlankamp** [comment]
Problem fixed in version 1.0.16
